name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    services:
      clinic_db:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv pip install --system --no-cache-dir .

      - name: Check lint with ruff
        run: |
          ruff check .
          ruff format --check .

      - name: Set test env
        run: |
          echo "postgres_host=localhost" >> $GITHUB_ENV
          echo "postgres_port=5432" >> $GITHUB_ENV
          echo "postgres_user=postgres" >> $GITHUB_ENV
          echo "postgres_password=postgres" >> $GITHUB_ENV
          echo "postgres_db=postgres" >> $GITHUB_ENV
          echo "debug=True" >> $GITHUB_ENV
          echo "secret_key=supersecret" >> $GITHUB_ENV
          echo "algorithm=HS256" >> $GITHUB_ENV
          echo "access_token_expire_minutes=30" >> $GITHUB_ENV
          echo "refresh_token_expire_days=7" >> $GITHUB_ENV

      - name: Test
        run: pytest
